name: Build and push a CRF-only docker image

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        type: string
        description: Docker image tag
        required: true
        default: "latest-crf"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build -x test

  docker-build:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Create more disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_LFOPPIANO }}
          password: ${{ secrets.DOCKERHUB_TOKEN_LFOPPIANO }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.crf
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lfoppiano/grobid:latest-develop, lfoppiano/grobid:${{ github.event.inputs.custom_tag}}